//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserves_sol
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mbaEntities : DbContext
    {
        public mbaEntities()
            : base("name=mbaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<oeuvre> oeuvre { get; set; }
        public DbSet<oeuvreparsondage> oeuvreparsondage { get; set; }
        public DbSet<sondage> sondage { get; set; }
    }
}
