//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserves_sol
{
    using System;
    using System.Collections.Generic;
    
    public partial class sondage
    {
        public sondage()
        {
            this.oeuvreparsondage = new HashSet<oeuvreparsondage>();
        }
    
        public int id { get; set; }
        public string titre { get; set; }
        public string description { get; set; }
        public System.DateTime date_debut { get; set; }
        public System.DateTime date_fin { get; set; }
        public int en_cours { get; set; }
    
        public virtual ICollection<oeuvreparsondage> oeuvreparsondage { get; set; }
    }
}
